version: '2'

services:
  app:
    container_name: studio-manager_app
    image: "studio-manager:latest"
    links:
      - "database:database"
    environment:
      NPS_ENV: "cloud"
    networks:
      - proxy
    volumes:
      - "app:/app"
    labels:
     # Frontend
     - "traefik.enable=true"
     - "traefik.http.routers.studio-manager.rule=Host(`studio-manager.nodea.studio`)"
     - "traefik.http.routers.studio-manager.entrypoints=websecure"
     - "traefik.http.services.studio-manager.loadbalancer.server.port=1337"
     - "traefik.http.routers.studio-manager.service=studio-manager"
     # TLS and security
     - "traefik.http.routers.studio-manager.tls=true"
     - "traefik.http.routers.studio-manager.tls.options=intermediate@file"
     - "traefik.http.routers.studio-manager.middlewares=secure-headers@file"
  database:
    container_name: studio-manager_database
    image: "nodeasoftware/nodea-database-mysql:latest"
    environment:
      MYSQL_DATABASE: "studio-manager"
      MYSQL_USER: "nodea"
      MYSQL_PASSWORD: "nodea"
      MYSQL_ROOT_PASSWORD: "nodea"
    networks:
      - proxy
    volumes:
      - "db_data:/var/lib/mysql"
      - "db_log:/var/log/mysql"

volumes:
  app:
  db_data:
  db_log:

networks:
  proxy:
    external:
      name: proxy
