version: '2'

services:
  container:
    image: "studio-manager:latest"
    links:
      - "database:database"
    environment:
      NPS_ENV: "cloud"
    networks:
      - proxy
    volumes:
      - "studio-manager_app:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:studio-manager.nodea.studio"
      - "traefik.port=1337"
  database:
    image: "nodea-database"
    environment:
      MYSQL_DATABASE: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - proxy
    volumes:
      - "studio-manager_db_data:/var/lib/mysql"
      - "studio-manager_db_log:/var/log/mysql"

volumes:
  studio-manager_app:
  studio-manager_db_data:
  studio-manager_db_log:
 
networks:
  proxy:
    external:
      name: proxy
